"""
SENTINEL Excel Report Generator
=====================================
Transforms investigation report JSON into a professional Excel workbook.
Single source of truth: the report object generated by ReportGenerator.

Architecture:
- No duplicate report generation logic
- Reuses existing report JSON
- Modular worksheet builders for each section
- Professional formatting (colors, borders, fonts)
- Investigator-ready workbook structure

Important: All generated workbooks must pass openpyxl validation before being returned.
This ensures compatibility with Microsoft Excel and other XLSX readers.
"""

import logging
import io
from datetime import datetime
from typing import Dict, Any, List, Optional
from openpyxl import Workbook, load_workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side,
    numbers
)
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo

logger = logging.getLogger(__name__)


class ExcelReportGenerator:
    """Generates professional Excel investigation reports from report JSON."""

    # Color palette (dark blue, grey, reds, etc.)
    COLORS = {
        "header_bg": "1F4E78",  # Dark blue
        "header_text": "FFFFFF",  # White
        "section_bg": "DCE6F1",  # Light blue
        "critical_risk": "FF4444",  # Red
        "high_risk": "FF9944",  # Orange
        "medium_risk": "FFDD44",  # Yellow
        "low_risk": "44DD44",  # Green
        "row_alt1": "F5F5F5",  # Light grey
        "row_alt2": "FFFFFF",  # White
        "border": "CCCCCC",  # Light grey border
    }

    RISK_LEVELS = {
        "CRITICAL": COLORS["critical_risk"],
        "HIGH": COLORS["high_risk"],
        "MEDIUM": COLORS["medium_risk"],
        "LOW": COLORS["low_risk"],
    }

    @staticmethod
    def format_inr(value: float) -> str:
        """Format number as Indian Rupees."""
        try:
            val_int = int(value)
            s = str(val_int)
            if len(s) <= 3:
                return f"₹{s}"
            last_three = s[-3:]
            other_parts = s[:-3]
            groups = []
            while other_parts:
                groups.append(other_parts[-2:])
                other_parts = other_parts[:-2]
            groups.reverse()
            formatted = ",".join(groups) + "," + last_three
            return f"₹{formatted}"
        except Exception:
            return f"₹{value:,.2f}"

    @staticmethod
    def get_risk_color(level: str) -> str:
        """Get color code for risk level."""
        level_upper = str(level).upper()
        return ExcelReportGenerator.RISK_LEVELS.get(level_upper, ExcelReportGenerator.COLORS["low_risk"])

    @staticmethod
    def create_header_style() -> Dict[str, Any]:
        """Create header cell style."""
        return {
            "font": Font(name="Calibri", size=11, bold=True, color=ExcelReportGenerator.COLORS["header_text"]),
            "fill": PatternFill(start_color=ExcelReportGenerator.COLORS["header_bg"], end_color=ExcelReportGenerator.COLORS["header_bg"], fill_type="solid"),
            "alignment": Alignment(horizontal="center", vertical="center", wrap_text=True),
            "border": Border(
                left=Side(style="thin", color=ExcelReportGenerator.COLORS["border"]),
                right=Side(style="thin", color=ExcelReportGenerator.COLORS["border"]),
                top=Side(style="thin", color=ExcelReportGenerator.COLORS["border"]),
                bottom=Side(style="thin", color=ExcelReportGenerator.COLORS["border"]),
            ),
        }

    @staticmethod
    def apply_style(cell, **styles):
        """Apply styles to a cell."""
        if "font" in styles:
            cell.font = styles["font"]
        if "fill" in styles:
            cell.fill = styles["fill"]
        if "alignment" in styles:
            cell.alignment = styles["alignment"]
        if "border" in styles:
            cell.border = styles["border"]
        if "number_format" in styles:
            cell.number_format = styles["number_format"]

    @classmethod
    def generate(cls, case: Dict[str, Any], report: Dict[str, Any], transactions: List[Dict[str, Any]]) -> bytes:
        """
        Generate Excel workbook from report JSON.

        Args:
            case: Case metadata (account_id, risk_score, etc.)
            report: Generated investigation report
            transactions: List of transactions

        Returns:
            Bytes of Excel workbook (validated XLSX format)

        Raises:
            ValueError: If generated workbook is invalid
        """
        case_id = case.get("account_id", "UNKNOWN")
        logger.info("[EXCEL] Starting workbook generation for case: {}".format(case_id))

        try:
            # Create workbook
            logger.debug("[EXCEL] Creating new workbook")
            wb = Workbook()
            ws = wb.active
            ws.title = "Executive Summary"

            # Build worksheets in order
            logger.debug("[EXCEL] Building Executive Summary sheet")
            cls._build_executive_summary(wb, case, report)

            logger.debug("[EXCEL] Building Investigation Summary sheet")
            cls._build_investigation_summary(wb, report)

            logger.debug("[EXCEL] Building Transactions sheet ({} transactions)".format(len(transactions)))
            cls._build_transactions(wb, transactions)

            logger.debug("[EXCEL] Building High Risk Transactions sheet")
            cls._build_high_risk_transactions(wb, report)

            logger.debug("[EXCEL] Building Detected Patterns sheet")
            cls._build_detected_patterns(wb, report)

            logger.debug("[EXCEL] Building Money Flow sheet")
            cls._build_money_flow(wb, report)

            logger.debug("[EXCEL] Building Entities sheet")
            cls._build_entities(wb, report)

            logger.debug("[EXCEL] Building Timeline sheet")
            cls._build_timeline(wb, report)

            logger.debug("[EXCEL] Building Beneficiaries sheet")
            cls._build_beneficiaries(wb, report)

            logger.debug("[EXCEL] Building Graph Statistics sheet")
            cls._build_graph_statistics(wb, report)

            logger.debug("[EXCEL] Building Parser Statistics sheet")
            cls._build_parser_statistics(wb, report)

            logger.debug("[EXCEL] Building Recommendations sheet")
            cls._build_recommendations(wb, report)

            logger.info("[EXCEL] Created {} worksheets".format(len(wb.sheetnames)))

            # Save to bytes
            logger.debug("[EXCEL] Saving workbook to BytesIO")
            output = io.BytesIO()
            wb.save(output)
            output.seek(0)
            excel_bytes = output.getvalue()
            logger.info("[EXCEL] Workbook saved: {} bytes".format(len(excel_bytes)))

            # Validate workbook can be reopened
            logger.debug("[EXCEL] Validating workbook integrity")
            cls._validate_workbook(excel_bytes, case_id)
            logger.info("[EXCEL] Workbook validation passed")

            return excel_bytes

        except Exception as e:
            logger.error("[EXCEL] Failed to generate workbook for case {}: {}".format(case_id, str(e)))
            raise

    @classmethod
    def _validate_workbook(cls, excel_bytes: bytes, case_id: str) -> None:
        """
        Validate that generated workbook is a valid XLSX file.

        Args:
            excel_bytes: Binary workbook data
            case_id: Case ID for logging

        Raises:
            ValueError: If workbook is invalid
        """
        logger.debug("[EXCEL] Validating workbook for case: {}".format(case_id))

        try:
            # Attempt to load workbook from bytes
            test_io = io.BytesIO(excel_bytes)
            test_wb = load_workbook(test_io)

            # Verify it has sheets
            if not test_wb.sheetnames:
                raise ValueError("Workbook contains no sheets")

            logger.debug("[EXCEL] Workbook has {} sheets: {}".format(
                len(test_wb.sheetnames),
                ", ".join(test_wb.sheetnames)
            ))

            # Verify Executive Summary sheet exists
            if "Executive Summary" not in test_wb.sheetnames:
                raise ValueError("Executive Summary sheet not found")

            logger.debug("[EXCEL] All validation checks passed for case: {}".format(case_id))

        except Exception as e:
            logger.error("[EXCEL] Validation failed for case {}: {}".format(case_id, str(e)))
            raise ValueError("Generated workbook is invalid: {}".format(str(e)))

    @classmethod
    def _build_executive_summary(cls, wb: Workbook, case: Dict[str, Any], report: Dict[str, Any]):
        """Build Executive Summary sheet."""
        ws = wb.active

        # Title
        ws.merge_cells("A1:D1")
        title = ws["A1"]
        title.value = f"SENTINEL Investigation Report"
        title.font = Font(name="Calibri", size=16, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        title.alignment = Alignment(horizontal="center", vertical="center")
        ws.row_dimensions[1].height = 25

        # Subtitle
        ws.merge_cells("A2:D2")
        subtitle = ws["A2"]
        subtitle.value = f"Case ID: {case.get('account_id', 'N/A')}"
        subtitle.font = Font(name="Calibri", size=11, color=cls.COLORS["header_text"])
        subtitle.fill = PatternFill(start_color=cls.COLORS["section_bg"], end_color=cls.COLORS["section_bg"], fill_type="solid")
        subtitle.alignment = Alignment(horizontal="center", vertical="center")
        ws.row_dimensions[2].height = 20

        row = 4

        # Key Metrics
        headers = ["Metric", "Value"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        metrics = [
            ("Case ID", case.get("account_id", "N/A")),
            ("Account Holder", case.get("holder_name", "Unknown")),
            ("Risk Score", f"{case.get('risk_score', 0):.0f}%"),
            ("Risk Level", case.get("risk_level", "LOW").upper()),
            ("Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        ]

        for metric, value in metrics:
            ws.cell(row, 1).value = metric
            ws.cell(row, 1).font = Font(bold=True)
            ws.cell(row, 2).value = value
            row += 1

        # Risk indicator color
        risk_cell = ws.cell(row - 4, 2)
        risk_color = cls.get_risk_color(case.get("risk_level", "LOW"))
        risk_cell.fill = PatternFill(start_color=risk_color, end_color=risk_color, fill_type="solid")
        risk_cell.font = Font(bold=True, color="FFFFFF" if case.get("risk_level", "LOW").upper() != "LOW" else "000000")

        row += 1

        # Executive Summary Text
        ws.cell(row, 1).value = "Executive Summary"
        ws.cell(row, 1).font = Font(size=12, bold=True)
        row += 1

        summary_text = report.get("executive_summary", "No summary available.")
        ws.merge_cells(f"A{row}:D{row+3}")
        summary_cell = ws.cell(row, 1)
        summary_cell.value = summary_text
        summary_cell.alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)
        ws.row_dimensions[row].height = 80
        row += 4

        # Recommended Next Steps
        row += 1
        ws.cell(row, 1).value = "Recommended Next Steps"
        ws.cell(row, 1).font = Font(size=12, bold=True)
        row += 1

        next_steps = report.get("recommended_next_steps", [])
        for step in next_steps:
            ws.cell(row, 1).value = f"• {step}"
            ws.cell(row, 1).alignment = Alignment(wrap_text=True)
            ws.row_dimensions[row].height = 30
            row += 1

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 40
        ws.column_dimensions["C"].width = 20
        ws.column_dimensions["D"].width = 20

    @classmethod
    def _build_investigation_summary(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Investigation Summary sheet."""
        ws = wb.create_sheet("Investigation Summary")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:D{row}")
        title = ws.cell(row, 1)
        title.value = "Investigation Summary"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Risk Explanation
        ws.cell(row, 1).value = "Risk Explanation"
        ws.cell(row, 1).font = Font(size=11, bold=True)
        row += 1

        risk_explanation = report.get("risk_explanation", "No explanation available.")
        ws.merge_cells(f"A{row}:D{row+2}")
        risk_cell = ws.cell(row, 1)
        risk_cell.value = risk_explanation
        risk_cell.alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)
        ws.row_dimensions[row].height = 60
        row += 4

        # Triggered Patterns
        ws.cell(row, 1).value = "Triggered Patterns"
        ws.cell(row, 1).font = Font(size=11, bold=True)
        row += 1

        patterns = report.get("detected_patterns", [])
        for pattern in patterns:
            pattern_name = pattern.get("name", "Unknown")
            pattern_desc = pattern.get("description", "No description")
            ws.cell(row, 1).value = pattern_name
            ws.cell(row, 2).value = pattern_desc
            ws.cell(row, 1).font = Font(bold=True)
            ws.row_dimensions[row].height = 25
            row += 1

        row += 1

        # Risk Factors
        ws.cell(row, 1).value = "Risk Factors"
        ws.cell(row, 1).font = Font(size=11, bold=True)
        row += 1

        explanations = report.get("investigation_risk", {}).get("explanation", [])
        for explanation in explanations:
            ws.merge_cells(f"A{row}:D{row}")
            ws.cell(row, 1).value = f"• {explanation}"
            ws.cell(row, 1).alignment = Alignment(wrap_text=True)
            ws.row_dimensions[row].height = 20
            row += 1

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 50
        ws.column_dimensions["C"].width = 20
        ws.column_dimensions["D"].width = 20

    @classmethod
    def _build_transactions(cls, wb: Workbook, transactions: List[Dict[str, Any]]):
        """Build Transactions sheet with all parsed transactions."""
        ws = wb.create_sheet("Transactions")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:H{row}")
        title = ws.cell(row, 1)
        title.value = f"All Transactions ({len(transactions)} total)"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Headers
        headers = ["Date", "Time", "Description", "Amount (₹)", "Type", "Channel", "Counterparty", "Risk Score"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        # Sort transactions by date
        sorted_txs = sorted(transactions, key=lambda x: x.get("timestamp", ""), reverse=True)

        for tx in sorted_txs:
            ws.cell(row, 1).value = tx.get("date", "N/A")
            ws.cell(row, 2).value = tx.get("time", "N/A")
            ws.cell(row, 3).value = tx.get("description", "N/A")
            ws.cell(row, 4).value = tx.get("amount", 0)
            ws.cell(row, 4).number_format = '#,##0.00'
            ws.cell(row, 5).value = "Debit" if tx.get("is_debit", True) else "Credit"
            ws.cell(row, 6).value = tx.get("channel", "N/A")
            ws.cell(row, 7).value = tx.get("sender_account" if tx.get("is_debit") else "receiver_account", "N/A")

            risk_score = tx.get("risk_score", 0)
            ws.cell(row, 8).value = f"{risk_score:.0f}%" if risk_score else "N/A"

            # Alternate row colors
            fill_color = cls.COLORS["row_alt1"] if row % 2 == 0 else cls.COLORS["row_alt2"]
            for col in range(1, 9):
                ws.cell(row, col).fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")

            row += 1

        # Freeze panes
        ws.freeze_panes = "A3"

        # Set column widths
        ws.column_dimensions["A"].width = 12
        ws.column_dimensions["B"].width = 12
        ws.column_dimensions["C"].width = 30
        ws.column_dimensions["D"].width = 15
        ws.column_dimensions["E"].width = 10
        ws.column_dimensions["F"].width = 12
        ws.column_dimensions["G"].width = 20
        ws.column_dimensions["H"].width = 12

    @classmethod
    def _build_high_risk_transactions(cls, wb: Workbook, report: Dict[str, Any]):
        """Build High Risk Transactions sheet."""
        ws = wb.create_sheet("High Risk Transactions")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:G{row}")
        title = ws.cell(row, 1)
        title.value = "High Risk Transactions"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Headers
        headers = ["Date", "Amount (₹)", "Risk Score", "Risk Level", "Description", "Counterparty", "Pattern Flag"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        high_risk_txs = report.get("high_risk_transactions", [])
        for tx in high_risk_txs:
            risk_score = tx.get("risk_score", tx.get("amount", 0))
            risk_level = "HIGH" if risk_score >= 60 else "MEDIUM" if risk_score >= 40 else "LOW"

            ws.cell(row, 1).value = tx.get("date", "N/A")
            ws.cell(row, 2).value = tx.get("amount", 0)
            ws.cell(row, 2).number_format = '#,##0.00'
            ws.cell(row, 3).value = f"{risk_score:.0f}%"
            ws.cell(row, 4).value = risk_level
            ws.cell(row, 5).value = tx.get("description", "N/A")
            ws.cell(row, 6).value = tx.get("sender_account", "N/A")
            ws.cell(row, 7).value = "Yes" if tx.get("pattern_flag") else "No"

            # Color code risk level
            risk_color = cls.get_risk_color(risk_level)
            for col in range(1, 8):
                cell = ws.cell(row, col)
                if col == 4:  # Risk level column
                    cell.fill = PatternFill(start_color=risk_color, end_color=risk_color, fill_type="solid")
                    cell.font = Font(bold=True, color="FFFFFF")

            row += 1

        ws.freeze_panes = "A3"

        # Set column widths
        for col in range(1, 8):
            ws.column_dimensions[get_column_letter(col)].width = 18

    @classmethod
    def _build_detected_patterns(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Detected Patterns sheet."""
        ws = wb.create_sheet("Detected Patterns")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:E{row}")
        title = ws.cell(row, 1)
        title.value = "Detected Patterns"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Headers
        headers = ["Pattern", "Severity", "Confidence", "Description", "Related Transactions"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        patterns = report.get("detected_patterns", [])
        for pattern in patterns:
            severity = pattern.get("severity", "MEDIUM").upper()

            ws.cell(row, 1).value = pattern.get("name", "Unknown")
            ws.cell(row, 2).value = severity
            ws.cell(row, 3).value = f"{pattern.get('confidence', 0):.0f}%"
            ws.cell(row, 4).value = pattern.get("description", "N/A")
            ws.cell(row, 5).value = pattern.get("related_transactions_count", 0)

            # Color code severity
            severity_color = cls.get_risk_color(severity)
            severity_cell = ws.cell(row, 2)
            severity_cell.fill = PatternFill(start_color=severity_color, end_color=severity_color, fill_type="solid")
            severity_cell.font = Font(bold=True, color="FFFFFF")

            row += 1

        ws.freeze_panes = "A3"

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 12
        ws.column_dimensions["C"].width = 12
        ws.column_dimensions["D"].width = 40
        ws.column_dimensions["E"].width = 20

    @classmethod
    def _build_money_flow(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Money Flow sheet."""
        ws = wb.create_sheet("Money Flow")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:F{row}")
        title = ws.cell(row, 1)
        title.value = "Money Flow Summary"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Money flow summary metrics
        money_flow = report.get("money_flow_summary", {})

        metrics = [
            ("Total Inflow", money_flow.get("total_inflow", 0)),
            ("Total Outflow", money_flow.get("total_outflow", 0)),
            ("Net Flow", money_flow.get("net_flow", 0)),
            ("Unique Counterparties", money_flow.get("unique_counterparties", 0)),
            ("Primary Flow Direction", money_flow.get("primary_flow_direction", "N/A")),
        ]

        for metric, value in metrics:
            ws.cell(row, 1).value = metric
            ws.cell(row, 1).font = Font(bold=True)
            if isinstance(value, (int, float)) and metric != "Unique Counterparties":
                ws.cell(row, 2).value = value
                ws.cell(row, 2).number_format = '#,##0.00'
            else:
                ws.cell(row, 2).value = str(value)
            row += 1

        row += 2

        # Money flow details (from graph or beneficiaries)
        ws.cell(row, 1).value = "Top Beneficiaries"
        ws.cell(row, 1).font = Font(size=12, bold=True)
        row += 1

        headers = ["Beneficiary", "Total Received (₹)", "Transaction Count"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        beneficiaries = report.get("top_beneficiaries", [])
        for benef in beneficiaries:
            ws.cell(row, 1).value = benef.get("account", benef.get("name", "Unknown"))
            ws.cell(row, 2).value = benef.get("total_received", 0)
            ws.cell(row, 2).number_format = '#,##0.00'
            ws.cell(row, 3).value = benef.get("tx_count", 0)
            row += 1

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 20
        ws.column_dimensions["C"].width = 20
        ws.column_dimensions["D"].width = 20
        ws.column_dimensions["E"].width = 20
        ws.column_dimensions["F"].width = 20

    @classmethod
    def _build_entities(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Extracted Entities sheet."""
        ws = wb.create_sheet("Entities")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:C{row}")
        title = ws.cell(row, 1)
        title.value = "Extracted Entities"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        entities = report.get("extracted_entities", {})

        # Helper function to build entity section
        def build_section(title, entity_list):
            nonlocal row
            if not entity_list:
                return

            ws.cell(row, 1).value = title
            ws.cell(row, 1).font = Font(size=11, bold=True)
            row += 1

            headers = ["Entity", "Occurrences", "Type"]
            for col, header in enumerate(headers, 1):
                cell = ws.cell(row, col)
                cell.value = header
                cls.apply_style(cell, **cls.create_header_style())
            row += 1

            for entity in entity_list:
                ws.cell(row, 1).value = entity.get("value", "N/A")
                ws.cell(row, 2).value = entity.get("occurrences", 1)
                ws.cell(row, 3).value = entity.get("type", "Unknown")
                row += 1

            row += 1

        # Build sections
        build_section("Names", entities.get("names", []))
        build_section("Accounts", entities.get("accounts", []))
        build_section("UPI IDs", entities.get("upi_ids", []))
        build_section("IFSC Codes", entities.get("ifsc", []))
        build_section("Beneficiaries", entities.get("beneficiaries", []))
        build_section("Merchants", entities.get("merchants", []))
        build_section("Banks", entities.get("banks", []))

        # Set column widths
        ws.column_dimensions["A"].width = 30
        ws.column_dimensions["B"].width = 15
        ws.column_dimensions["C"].width = 20

    @classmethod
    def _build_timeline(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Timeline sheet."""
        ws = wb.create_sheet("Timeline")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:F{row}")
        title = ws.cell(row, 1)
        title.value = "Investigation Timeline"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Headers
        headers = ["Timestamp", "Event", "Amount (₹)", "Risk Flag", "Pattern", "Counterparty"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        timeline = report.get("timeline", [])
        for event in timeline:
            ws.cell(row, 1).value = event.get("date", "N/A")
            ws.cell(row, 2).value = event.get("event", "N/A")

            amount = event.get("amount", 0)
            if amount:
                ws.cell(row, 3).value = amount
                ws.cell(row, 3).number_format = '#,##0.00'

            ws.cell(row, 4).value = "Yes" if event.get("risk_flag") else "No"
            ws.cell(row, 5).value = event.get("pattern", "N/A")
            ws.cell(row, 6).value = event.get("counterparty", "N/A")

            # Alternate row colors
            fill_color = cls.COLORS["row_alt1"] if row % 2 == 0 else cls.COLORS["row_alt2"]
            for col in range(1, 7):
                ws.cell(row, col).fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")

            row += 1

        ws.freeze_panes = "A3"

        # Set column widths
        ws.column_dimensions["A"].width = 18
        ws.column_dimensions["B"].width = 25
        ws.column_dimensions["C"].width = 15
        ws.column_dimensions["D"].width = 12
        ws.column_dimensions["E"].width = 20
        ws.column_dimensions["F"].width = 20

    @classmethod
    def _build_beneficiaries(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Beneficiaries sheet."""
        ws = wb.create_sheet("Beneficiaries")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:E{row}")
        title = ws.cell(row, 1)
        title.value = "Beneficiary Analysis"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Headers
        headers = ["Beneficiary", "Account", "Total Received (₹)", "Transaction Count", "Risk Indicator"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        beneficiaries = report.get("top_beneficiaries", [])
        for benef in beneficiaries:
            ws.cell(row, 1).value = benef.get("name", benef.get("account", "Unknown"))
            ws.cell(row, 2).value = benef.get("account", "N/A")

            total_received = benef.get("total_received", 0)
            ws.cell(row, 3).value = total_received
            ws.cell(row, 3).number_format = '#,##0.00'

            tx_count = benef.get("tx_count", 0)
            ws.cell(row, 4).value = tx_count

            # Risk indicator based on transaction count
            if tx_count > 10:
                risk = "High Frequency"
                color = cls.COLORS["high_risk"]
            elif tx_count > 5:
                risk = "Medium Frequency"
                color = cls.COLORS["medium_risk"]
            else:
                risk = "Low Frequency"
                color = cls.COLORS["low_risk"]

            ws.cell(row, 5).value = risk
            ws.cell(row, 5).fill = PatternFill(start_color=color, end_color=color, fill_type="solid")

            row += 1

        ws.freeze_panes = "A3"

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 25
        ws.column_dimensions["C"].width = 18
        ws.column_dimensions["D"].width = 18
        ws.column_dimensions["E"].width = 18

    @classmethod
    def _build_graph_statistics(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Graph Statistics sheet."""
        ws = wb.create_sheet("Graph Statistics")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:D{row}")
        title = ws.cell(row, 1)
        title.value = "Graph & Network Statistics"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        graph_summary = report.get("graph_summary", {})

        metrics = [
            ("Total Nodes", graph_summary.get("total_nodes", 0)),
            ("Total Edges", graph_summary.get("total_edges", 0)),
        ]

        for metric, value in metrics:
            ws.cell(row, 1).value = metric
            ws.cell(row, 1).font = Font(bold=True)
            ws.cell(row, 2).value = value
            row += 1

        row += 1

        # Node types breakdown
        ws.cell(row, 1).value = "Node Types Distribution"
        ws.cell(row, 1).font = Font(size=11, bold=True)
        row += 1

        headers = ["Node Type", "Count"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        node_types = graph_summary.get("node_types", {})
        for node_type, count in node_types.items():
            ws.cell(row, 1).value = node_type
            ws.cell(row, 2).value = count
            row += 1

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 20
        ws.column_dimensions["C"].width = 20
        ws.column_dimensions["D"].width = 20

    @classmethod
    def _build_parser_statistics(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Parser Statistics sheet."""
        ws = wb.create_sheet("Parser Statistics")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:D{row}")
        title = ws.cell(row, 1)
        title.value = "Parser Statistics & Quality Metrics"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        parser_stats = report.get("parser_statistics", {})

        metrics = [
            ("Rows Parsed", parser_stats.get("rows_parsed", 0)),
            ("Rows Skipped", parser_stats.get("rows_skipped", 0)),
            ("Parser Confidence", f"{parser_stats.get('parser_confidence', 0):.1f}%"),
            ("Detected Format", parser_stats.get("detected_format", "Unknown")),
            ("Source File", parser_stats.get("source_file", "N/A")),
        ]

        for metric, value in metrics:
            ws.cell(row, 1).value = metric
            ws.cell(row, 1).font = Font(bold=True)
            ws.cell(row, 2).value = str(value)
            row += 1

        row += 1

        # Warnings
        warnings = parser_stats.get("warnings", [])
        if warnings:
            ws.cell(row, 1).value = "Warnings"
            ws.cell(row, 1).font = Font(size=11, bold=True)
            row += 1

            for warning in warnings:
                ws.merge_cells(f"A{row}:D{row}")
                ws.cell(row, 1).value = f"⚠ {warning}"
                ws.cell(row, 1).alignment = Alignment(wrap_text=True)
                ws.row_dimensions[row].height = 20
                row += 1

        # Set column widths
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 40
        ws.column_dimensions["C"].width = 20
        ws.column_dimensions["D"].width = 20

    @classmethod
    def _build_recommendations(cls, wb: Workbook, report: Dict[str, Any]):
        """Build Recommendations sheet."""
        ws = wb.create_sheet("Recommendations")

        row = 1

        # Title
        ws.merge_cells(f"A{row}:D{row}")
        title = ws.cell(row, 1)
        title.value = "Investigation Recommendations"
        title.font = Font(size=14, bold=True, color=cls.COLORS["header_text"])
        title.fill = PatternFill(start_color=cls.COLORS["header_bg"], end_color=cls.COLORS["header_bg"], fill_type="solid")
        ws.row_dimensions[row].height = 20
        row += 2

        # Headers
        headers = ["Priority", "Recommendation", "Reason", "Status"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row, col)
            cell.value = header
            cls.apply_style(cell, **cls.create_header_style())
        row += 1

        next_steps = report.get("recommended_next_steps", [])
        priority_levels = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

        for idx, step in enumerate(next_steps):
            # Assign priority based on index
            priority = priority_levels[min(idx, len(priority_levels) - 1)]

            ws.cell(row, 1).value = priority

            priority_color = cls.get_risk_color(priority)
            priority_cell = ws.cell(row, 1)
            priority_cell.fill = PatternFill(start_color=priority_color, end_color=priority_color, fill_type="solid")
            priority_cell.font = Font(bold=True, color="FFFFFF")

            ws.merge_cells(f"B{row}:C{row}")
            ws.cell(row, 2).value = step
            ws.cell(row, 2).alignment = Alignment(wrap_text=True)

            ws.cell(row, 4).value = "Pending"
            ws.cell(row, 4).alignment = Alignment(horizontal="center")

            ws.row_dimensions[row].height = 35
            row += 1

        # Set column widths
        ws.column_dimensions["A"].width = 12
        ws.column_dimensions["B"].width = 45
        ws.column_dimensions["C"].width = 25
        ws.column_dimensions["D"].width = 12

        ws.freeze_panes = "A3"
